name: Test the analyze and test workflow

on:
  push:
    branches-ignore: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/analyze-test.yml@v4
    with:
      module-name: 'mqttreplicate'
      python-version: '3.13'
      weewx-version: '5.1.0'
      latest-python-version: '3.13'
      latest-weewx-version: '5.1.0'
      pip-list: 'paho-mqtt'
      package-list: 'mosquitto'
      integration-test: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
