name: Analyze and test

on:
  push:
    branches-ignore: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development-tools/.github/workflows/analyze-test.yml@v4
    with:
      module-name: 'mqttreplicate'
      pip-list: 'paho-mqtt'
      package-list: 'mosquitto'
      function-test: false
      integration-test: false
      e2e-test: false
      #flake-extra-parms: '--exclude tests'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
