name: Test the full analyze and test workflow

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/full-analyze-test.yml@v4
    with:
      module-name: 'mqttreplicate'
      pip-list: 'paho-mqtt'
      package-list: 'mosquitto'
      integration-test: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}