name: Analyze and test matrix

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development-tools/.github/workflows/analyze-test-matrix.yml@v4
    with:
      module-name: 'mqttreplicate'
      pip-list: 'paho-mqtt'
      package-list: 'mosquitto'
      function-test: false
      integration-test: false
      e2e-test: false
      #flake-extra-parms: '--exclude tests'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Run tests agains paho-mqtt 1.6.1
  analyze-test-paho-mqtt-1-6-1:
    uses: weewx-extensions/development-tools/.github/workflows/analyze-test.yml@v4
    with:
      module-name: 'mqttreplicate'
      pip-list: 'paho-mqtt==1.6.1'
      package-list: 'mosquitto'
      artifact-name-suffix: '-2'
      function-test: false
      integration-test: false
      e2e-test: false
      #flake-extra-parms: '--exclude tests'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}