name: Stale Issues

on:
  schedule:
  - cron: "0 0 * * *"
  # - cron: "25 * * * *"
  #workflow_dispatch:

jobs:
  stale:
    uses: weewx-extensions/development-tools/.github/workflows/stale.yml@latest
